### ISSUE TITLE
SpringBoot3.0 RC 启动报错Property 'sqlSessionFactory' or 'sqlSessionTemplate' are required

### ISSUE THREAD

**Issue by ijry** [baomidou/mybatis-plus#4908] opened 2022-10-26 11:12 UTC
### 当前使用版本(必填,否则不予处理)
3.5.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用spring-boot3.0 RC

### 重现步骤(如果有就写完整)

直接引入库后，创建一个Mapper继承BaseMapper

### 报错信息

Property 'sqlSessionFactory' or 'sqlSessionTemplate' are required

**Comment by linghengqian** [comment] 2022-10-26 11:41
- Duplicate of https://github.com/baomidou/mybatis-plus/pull/4870 , you need to specify the snapshot version of https://oss.sonatype.org/content/repositories/snapshots/ for both mybatis and mybatis-plus.  

- This issue should be marked invalid and closed.

**Comment by csx-bill** [comment] 2022-11-04 08:21
[demo.zip](https://github.com/baomidou/mybatis-plus/files/9936299/demo.zip)

**Comment by csx-bill** [comment] 2022-11-04 08:23
出现这个问题的 demo    环境  jdk  graalvm-ce-java17-22.3.0

**Comment by qlshouyu** [comment] 2022-11-22 08:44
解决了吗？我使用spring-boot3.0 RC2 也有相同的问题，使用的是mybatis-plus-boot-starter:3.5.2

**Comment by qlshouyu** [comment] 2022-11-22 09:13
Good,it worked!! Thank you linghengqian;[https://github.com/baomidou/mybatis-plus/pull/4870](https://github.com/baomidou/mybatis-plus/pull/4870)

**Comment by ijry** [comment] 2022-11-23 01:13
> * Duplicate of [Adapting SpringBoot OSS 3.0.0-M5 to the changes made to the auto-config class #4870](https://github.com/baomidou/mybatis-plus/pull/4870) , you need to specify the snapshot version of https://oss.sonatype.org/content/repositories/snapshots/ for both mybatis and mybatis-plus.
> * This issue should be marked invalid and closed.

could you look at this issue ?  [https://github.com/dromara/Sa-Token/issues/337](https://github.com/dromara/Sa-Token/issues/337) thks.

**Comment by linghengqian** [comment] 2022-11-26 04:39
> > * Duplicate of [Adapting SpringBoot OSS 3.0.0-M5 to the changes made to the auto-config class #4870](https://github.com/baomidou/mybatis-plus/pull/4870) , you need to specify the snapshot version of https://oss.sonatype.org/content/repositories/snapshots/ for both mybatis and mybatis-plus.
> > * This issue should be marked invalid and closed.
> 
> could you look at this issue ?  [https://github.com/dromara/Sa-Token/issues/337](https://github.com/dromara/Sa-Token/issues/337) thks.

- Late reply, the issue of sa-token has nothing to do with me, you can directly submit PR to them.

- The current issue should be closed and marked as invalid.

**Comment by huayanYu** [comment] 2022-12-21 11:44
#4971

**Closed as completed by huayanYu** 2022-12-21 11:44 UTC
